blank_issues_enabled: false                                    
contact_links:                                                 
  - name: Questions and discussions                            
    url: https://github.com/airdcpp/airdcpp-windows/discussions
    about: If you need help or have something to discuss       
                                                               